<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="tlvyanaf1lt" name="com.verifone.tests.oldTests.CGApplicationPage" tests="23" failures="2" timestamp="01 May 2018 15:49:01 GMT" time="447.836" errors="0">
  <testcase name="CGApplicationPageMandatoryFields" time="12.293" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMaxLengthValue" time="18.623" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="12.859" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMaxLengthValue" time="17.397" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMaxLengthValue" time="79.404" classname="com.verifone.tests.oldTests.CGApplicationPage">
    <failure type="java.lang.AssertionError" message="expected [Succeeded.] but found [Error message not found!]">
        <![CDATA[java.lang.AssertionError: expected [Succeeded.] but found [Error message not found!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.verifone.tests.oldTests.CGApplicationPage.CGApplicationPageMaxLengthValue(CGApplicationPage.java:897)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CGApplicationPageMaxLengthValue -->
  <testcase name="CGApplicationPageTypeValidation" time="15.472" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="15.424" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMandatoryFields" time="8.799" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="15.326" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMandatoryFields" time="12.163" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="12.332" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageTypeValidation" time="16.969" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMandatoryFields" time="71.937" classname="com.verifone.tests.oldTests.CGApplicationPage">
    <failure type="java.lang.AssertionError" message="expected [Field is Required] but found [Error message not found!]">
        <![CDATA[java.lang.AssertionError: expected [Field is Required] but found [Error message not found!]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.verifone.tests.oldTests.CGApplicationPage.CGApplicationPageMandatoryFields(CGApplicationPage.java:229)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- CGApplicationPageMandatoryFields -->
  <testcase name="CGApplicationPageErrorHandling" time="15.705" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMandatoryFields" time="8.982" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="15.675" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMandatoryFields" time="8.950" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="12.744" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageTypeValidation" time="21.454" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageErrorHandling" time="15.535" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageTypeValidation" time="15.355" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageMandatoryFields" time="8.889" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
  <testcase name="CGApplicationPageTypeValidation" time="15.549" classname="com.verifone.tests.oldTests.CGApplicationPage"/>
</testsuite> <!-- com.verifone.tests.CGApplicationPage -->
